-- V1 baseline
--
-- Consolidated schema, generated on 2026-08-17 by replaying the former V1..V15
-- migrations against a real PostgreSQL 16 instance and dumping the resulting
-- schema (pg_dump --schema-only), then folding the reference-table seeds back in
-- at the end of this file.
--
-- THIRD consolidation of this file. The header it replaces recorded the first
-- two (2026-08-12 schema-only, 2026-08-13 folding the seeds back in) and ended
-- with the rule this one is knowingly breaking: "Any future schema change is a
-- new Vn file, never an edit to this one". That rule still holds for a schema
-- change. Squashing is a different act, and it has one hard prerequisite.
--
-- WHAT THIS COSTS: every existing database must be DROPPED AND RECREATED. Their
-- flyway_schema_history records 15 applied migrations that no longer resolve to
-- any file, and V1's own checksum has changed - Flyway refuses to start against
-- either. There is no repair path short of `flyway repair` plus a hand-rebuilt
-- history, so a deliberate reset of dev, recette and production is the price,
-- and it is why this is done between deployments rather than as part of one.
--
-- WHAT WAS DROPPED ON PURPOSE, and would be wrong to look for here:
--   * the ALTERs of V3, V6, V8..V12, V15 - their effect is already in the
--     CREATE TABLE statements below, which is the whole point of a squash;
--   * the two backfills (V6's convocation_delivery, V12's convocation_reply).
--     Both migrated rows that already existed; on an empty database they select
--     nothing, and carrying them would only suggest they still do something.
-- The seeds were NOT dropped - they are the one thing a --schema-only squash
-- silently loses, and doing so twice is what the previous header is about.
--
-- The dev profile cannot run this file (H2, Flyway disabled, schema generated by
-- Hibernate). Its copies of the four catalog seeds live in db/seed/ and are
-- loaded through spring.sql.init; ConvocationChannelSeedTest, ReplyMediumSeedTest
-- and RolePermissionSeedTest fail the build if the two ever drift apart.

--
-- Name: reject_journal_entry_line_mutation_when_not_draft(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.reject_journal_entry_line_mutation_when_not_draft() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    parent_status VARCHAR(20);
BEGIN
    SELECT status INTO parent_status FROM journal_entry WHERE id = COALESCE(NEW.journal_entry_id, OLD.journal_entry_id);
    IF parent_status IS DISTINCT FROM 'DRAFT' THEN
        RAISE EXCEPTION 'journal_entry_line for entry % cannot be inserted, updated or deleted once the entry left DRAFT (I4/ADR 0001)',
            COALESCE(NEW.journal_entry_id, OLD.journal_entry_id);
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;


--
-- Name: reject_journal_entry_mutation(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.reject_journal_entry_mutation() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'journal_entry % can never be physically deleted (I4/ADR 0001)', OLD.id;
    END IF;
    IF OLD.status = 'DRAFT' THEN
        RETURN NEW;
    END IF;
    IF OLD.status = 'POSTED' AND NEW.status = 'REVERSED' THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'journal_entry % is not DRAFT and cannot be mutated except DRAFT->POSTED or POSTED->REVERSED (I4/ADR 0001)', OLD.id;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounting_exercise; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounting_exercise (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    label character varying(200) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    status character varying(20) NOT NULL,
    closed_at timestamp with time zone,
    closed_by_user_id uuid,
    comment character varying(1000),
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: agenda_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agenda_item (
    id uuid NOT NULL,
    general_meeting_id uuid NOT NULL,
    label character varying(200) NOT NULL,
    description text,
    "position" integer NOT NULL,
    majority_rule character varying(20) NOT NULL,
    vote_session_status character varying(20) DEFAULT 'NOT_OPENED'::character varying NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_agenda_item_majority_rule CHECK (((majority_rule)::text = ANY ((ARRAY['SIMPLE'::character varying, 'ABSOLUTE'::character varying, 'UNANIMITY'::character varying])::text[]))),
    CONSTRAINT chk_agenda_item_position CHECK (("position" >= 0)),
    CONSTRAINT chk_agenda_item_vote_session CHECK (((vote_session_status)::text = ANY ((ARRAY['NOT_OPENED'::character varying, 'OPEN'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: allocation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.allocation (
    id uuid NOT NULL,
    debit_line_id uuid NOT NULL,
    credit_line_id uuid NOT NULL,
    amount numeric(14,2) NOT NULL,
    allocated_date date NOT NULL,
    allocated_by_user_id uuid NOT NULL,
    created_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT allocation_amount_check CHECK ((amount > (0)::numeric))
);


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user (
    id uuid NOT NULL,
    email character varying(150) NOT NULL,
    full_name character varying(200) NOT NULL,
    password_hash character varying(255) NOT NULL,
    verified boolean DEFAULT false NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    phone character varying(20),
    avatar bytea,
    avatar_content_type character varying(100)
);


--
-- Name: app_user_party; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user_party (
    app_user_id uuid NOT NULL,
    party_id uuid NOT NULL
);


--
-- Name: app_user_party_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user_party_role (
    app_user_id uuid NOT NULL,
    party_id uuid NOT NULL,
    property_id uuid NOT NULL,
    role character varying(30) NOT NULL
);


--
-- Name: board_member; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board_member (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    party_id uuid NOT NULL,
    board_role character varying(30) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    status character varying(30) DEFAULT 'ACTIVE'::character varying NOT NULL,
    user_id uuid
);


--
-- Name: building; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.building (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    floor_count integer NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: conversation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversation (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    type character varying(20) NOT NULL,
    created_by uuid NOT NULL,
    subject character varying(200),
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    concerns_unit character varying(100),
    CONSTRAINT chk_conversation_concerns_unit CHECK (((concerns_unit IS NULL) OR ((type)::text = 'GROUP'::text))),
    CONSTRAINT chk_conversation_subject CHECK (((((type)::text = ANY (ARRAY[('GROUP'::character varying)::text, ('BOARD_PRIVATE'::character varying)::text])) AND (subject IS NOT NULL)) OR (((type)::text = 'BROADCAST'::text) AND (subject IS NULL)))),
    CONSTRAINT conversation_type_check CHECK (((type)::text = ANY (ARRAY[('GROUP'::character varying)::text, ('BOARD_PRIVATE'::character varying)::text, ('BROADCAST'::character varying)::text])))
);


--
-- Name: conversation_participant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversation_participant (
    conversation_id uuid NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: conversation_read_marker; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversation_read_marker (
    conversation_id uuid NOT NULL,
    user_id uuid NOT NULL,
    last_read_message_id uuid,
    last_read_at timestamp with time zone
);


--
-- Name: convocation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.convocation (
    id uuid NOT NULL,
    general_meeting_id uuid NOT NULL,
    unit_id uuid NOT NULL,
    voting_weight numeric(12,2) NOT NULL,
    attendance_reply character varying(20) DEFAULT 'NO_REPLY'::character varying NOT NULL,
    replied_at timestamp with time zone,
    checked_in boolean DEFAULT false NOT NULL,
    attendance_mode character varying(20),
    checked_in_party_id uuid,
    checked_in_at timestamp with time zone,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    reply_source character varying(20),
    replied_by_party_id uuid,
    reply_note character varying(500),
    confirmation_token character varying(64) NOT NULL,
    confirmation_code character varying(6) NOT NULL,
    reply_medium character varying(30),
    reply_attendance_mode character varying(20),
    reply_by_proxy boolean DEFAULT false NOT NULL,
    CONSTRAINT chk_convocation_attendance_mode CHECK (((attendance_mode IS NULL) OR ((attendance_mode)::text = ANY ((ARRAY['ON_SITE'::character varying, 'REMOTE'::character varying])::text[])))),
    CONSTRAINT chk_convocation_attendance_reply CHECK (((attendance_reply)::text = ANY ((ARRAY['ATTENDING'::character varying, 'NOT_ATTENDING'::character varying, 'NO_REPLY'::character varying])::text[]))),
    CONSTRAINT chk_convocation_check_in CHECK (((checked_in = false) OR ((attendance_mode IS NOT NULL) AND (checked_in_at IS NOT NULL)))),
    CONSTRAINT chk_convocation_reply_attendance_mode CHECK ((((attendance_reply)::text = 'ATTENDING'::text) OR ((reply_attendance_mode IS NULL) AND (NOT reply_by_proxy)))),
    CONSTRAINT chk_convocation_reply_medium CHECK (((reply_medium IS NULL) OR ((reply_source)::text = 'OTHER'::text))),
    CONSTRAINT chk_convocation_reply_mode_value CHECK (((reply_attendance_mode IS NULL) OR ((reply_attendance_mode)::text = ANY ((ARRAY['ON_SITE'::character varying, 'REMOTE'::character varying])::text[])))),
    CONSTRAINT chk_convocation_reply_source CHECK (((reply_source IS NULL) OR ((reply_source)::text = ANY ((ARRAY['OWNER_APP'::character varying, 'OWNER_LINK'::character varying, 'OTHER'::character varying])::text[])))),
    CONSTRAINT chk_convocation_reply_source_present CHECK ((((attendance_reply)::text = 'NO_REPLY'::text) = (reply_source IS NULL))),
    CONSTRAINT chk_convocation_voting_weight CHECK ((voting_weight >= (0)::numeric))
);


--
-- Name: convocation_channel; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.convocation_channel (
    code character varying(30) NOT NULL,
    label character varying(100) NOT NULL,
    automated boolean DEFAULT false NOT NULL,
    "position" integer NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: convocation_delivery; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.convocation_delivery (
    id uuid NOT NULL,
    convocation_id uuid NOT NULL,
    channel_code character varying(30) NOT NULL,
    status character varying(20) NOT NULL,
    sent_at timestamp with time zone,
    reference character varying(100),
    recorded_by_user_id uuid,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    is_reminder boolean DEFAULT false NOT NULL,
    CONSTRAINT chk_convocation_delivery_reminder_reference CHECK (((NOT is_reminder) OR (reference IS NULL))),
    CONSTRAINT chk_convocation_delivery_sent_at CHECK ((((status)::text = 'SENT'::text) = (sent_at IS NOT NULL))),
    CONSTRAINT chk_convocation_delivery_status CHECK (((status)::text = ANY ((ARRAY['SENT'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: convocation_reply; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.convocation_reply (
    id uuid NOT NULL,
    convocation_id uuid NOT NULL,
    attendance_reply character varying(20) NOT NULL,
    reply_source character varying(20) NOT NULL,
    reply_medium character varying(30),
    replied_by_party_id uuid,
    note character varying(500),
    received_at timestamp with time zone NOT NULL,
    recorded_by_user_id uuid,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    attendance_mode character varying(20),
    by_proxy boolean DEFAULT false NOT NULL,
    CONSTRAINT chk_convocation_reply_attendance CHECK (((attendance_reply)::text = ANY ((ARRAY['ATTENDING'::character varying, 'NOT_ATTENDING'::character varying, 'NO_REPLY'::character varying])::text[]))),
    CONSTRAINT chk_convocation_reply_attendance_mode CHECK ((((attendance_reply)::text = 'ATTENDING'::text) OR ((attendance_mode IS NULL) AND (NOT by_proxy)))),
    CONSTRAINT chk_convocation_reply_medium CHECK (((reply_medium IS NULL) OR ((reply_source)::text = 'OTHER'::text))),
    CONSTRAINT chk_convocation_reply_mode_value CHECK (((attendance_mode IS NULL) OR ((attendance_mode)::text = ANY ((ARRAY['ON_SITE'::character varying, 'REMOTE'::character varying])::text[])))),
    CONSTRAINT chk_convocation_reply_source CHECK (((reply_source)::text = ANY ((ARRAY['OWNER_APP'::character varying, 'OWNER_LINK'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: device_push_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.device_push_token (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    expo_push_token character varying(200) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: document; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document (
    id uuid NOT NULL,
    owner_type character varying(20) NOT NULL,
    owner_id uuid NOT NULL,
    file_name character varying(255) NOT NULL,
    content_type character varying(100) NOT NULL,
    size_bytes bigint NOT NULL,
    storage_key character varying(255) NOT NULL,
    checksum_sha256 character varying(64) NOT NULL,
    uploaded_by uuid NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: expense; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expense (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    date date NOT NULL,
    ledger_account_id uuid NOT NULL,
    amount numeric(14,2) NOT NULL,
    description character varying(1000),
    receipt_reference character varying(200),
    journal_entry_id uuid NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT expense_amount_check CHECK ((amount > (0)::numeric))
);


--
-- Name: general_meeting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.general_meeting (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    meeting_type character varying(20) NOT NULL,
    status character varying(20) DEFAULT 'DRAFT'::character varying NOT NULL,
    title character varying(200) NOT NULL,
    scheduled_at timestamp with time zone,
    venue_type character varying(20),
    venue_address character varying(250),
    venue_link character varying(500),
    quorum_percentage numeric(5,2) NOT NULL,
    voting_weight_mode character varying(20) NOT NULL,
    opened_without_quorum boolean DEFAULT false NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    comment text,
    public_reference character varying(6) NOT NULL,
    CONSTRAINT chk_general_meeting_quorum_percentage CHECK (((quorum_percentage >= (0)::numeric) AND (quorum_percentage <= (100)::numeric))),
    CONSTRAINT chk_general_meeting_scheduled CHECK ((((status)::text = 'DRAFT'::text) OR ((scheduled_at IS NOT NULL) AND (venue_type IS NOT NULL)))),
    CONSTRAINT chk_general_meeting_status CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SCHEDULED'::character varying, 'CONVENED'::character varying, 'IN_PROGRESS'::character varying, 'CLOSED'::character varying, 'MINUTES_PUBLISHED'::character varying])::text[]))),
    CONSTRAINT chk_general_meeting_type CHECK (((meeting_type)::text = ANY ((ARRAY['ORDINARY'::character varying, 'EXTRAORDINARY'::character varying])::text[]))),
    CONSTRAINT chk_general_meeting_venue CHECK (((venue_type IS NULL) OR (((venue_type)::text = 'PHYSICAL'::text) AND (venue_address IS NOT NULL)) OR (((venue_type)::text = 'VIDEOCONFERENCE'::text) AND (venue_link IS NOT NULL)) OR (((venue_type)::text = 'HYBRID'::text) AND (venue_address IS NOT NULL) AND (venue_link IS NOT NULL)))),
    CONSTRAINT chk_general_meeting_weight_mode CHECK (((voting_weight_mode)::text = ANY ((ARRAY['PER_UNIT'::character varying, 'SHARES'::character varying])::text[])))
);


--
-- Name: installment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.installment (
    id uuid NOT NULL,
    unit_id uuid NOT NULL,
    due_date date NOT NULL,
    amount numeric(12,2) NOT NULL,
    installment_call_id uuid,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    outstanding_amount numeric(12,2) NOT NULL,
    journal_entry_line_id uuid
);


--
-- Name: installment_call; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.installment_call (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    period date NOT NULL,
    due_date date NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    status character varying(20) NOT NULL,
    journal_entry_id uuid
);


--
-- Name: invitation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invitation (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    type character varying(30) NOT NULL,
    target_role character varying(30) NOT NULL,
    target_email character varying(150),
    token character varying(255) NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_by_user_id uuid NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    consumed_email character varying(150),
    target_board_role character varying(50),
    CONSTRAINT chk_invitation_email_required CHECK ((((type)::text = 'PUBLIC'::text) OR (target_email IS NOT NULL)))
);


--
-- Name: journal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.journal (
    code character varying(4) NOT NULL,
    label character varying(100) NOT NULL,
    type character varying(20) NOT NULL,
    treasury_role character varying(30),
    postable boolean DEFAULT true NOT NULL
);


--
-- Name: journal_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.journal_entry (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    exercise_id uuid NOT NULL,
    period_id uuid NOT NULL,
    journal_code character varying(4) NOT NULL,
    treasury_account_id uuid,
    piece_date date NOT NULL,
    piece_number integer,
    external_reference character varying(200),
    status character varying(20) NOT NULL,
    original_entry_id uuid,
    created_by_user_id uuid NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: journal_entry_line; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.journal_entry_line (
    id uuid NOT NULL,
    journal_entry_id uuid NOT NULL,
    line_order integer NOT NULL,
    ledger_account_id uuid NOT NULL,
    auxiliary_unit_id uuid,
    auxiliary_party_id uuid,
    direction character varying(10) NOT NULL,
    amount numeric(14,2) NOT NULL,
    label character varying(200) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT journal_entry_line_amount_check CHECK ((amount > (0)::numeric))
);


--
-- Name: ledger_account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ledger_account (
    id uuid NOT NULL,
    property_id uuid,
    unit_id uuid,
    account_number character varying(8) NOT NULL,
    label character varying(200) NOT NULL,
    account_class integer NOT NULL,
    nature character varying(20) NOT NULL,
    collective boolean DEFAULT false NOT NULL,
    role character varying(30),
    active boolean DEFAULT true NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    balance numeric(14,2) DEFAULT 0 NOT NULL,
    bank_account_number character varying(64),
    CONSTRAINT chk_ledger_account_unit_requires_property CHECK (((unit_id IS NULL) OR (property_id IS NOT NULL)))
);


--
-- Name: ledger_account_number_sequence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ledger_account_number_sequence (
    property_id uuid NOT NULL,
    number_prefix character varying(6) NOT NULL,
    next_increment integer DEFAULT 1 NOT NULL
);


--
-- Name: meeting_minutes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meeting_minutes (
    id uuid NOT NULL,
    general_meeting_id uuid NOT NULL,
    content text NOT NULL,
    status character varying(20) DEFAULT 'DRAFT'::character varying NOT NULL,
    published_at timestamp with time zone,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_meeting_minutes_published CHECK ((((status)::text <> 'PUBLISHED'::text) OR (published_at IS NOT NULL))),
    CONSTRAINT chk_meeting_minutes_status CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'UNDER_REVIEW'::character varying, 'PUBLISHED'::character varying])::text[])))
);


--
-- Name: meeting_quorum_setting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meeting_quorum_setting (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    meeting_type character varying(20) NOT NULL,
    quorum_percentage numeric(5,2) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_meeting_quorum_setting_percentage CHECK (((quorum_percentage >= (0)::numeric) AND (quorum_percentage <= (100)::numeric))),
    CONSTRAINT chk_meeting_quorum_setting_type CHECK (((meeting_type)::text = ANY ((ARRAY['ORDINARY'::character varying, 'EXTRAORDINARY'::character varying])::text[])))
);


--
-- Name: membership_request; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.membership_request (
    id uuid NOT NULL,
    invitation_id uuid NOT NULL,
    property_id uuid NOT NULL,
    unit_id uuid NOT NULL,
    party_id uuid NOT NULL,
    user_id uuid NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    decided_at timestamp with time zone,
    decided_by_user_id uuid,
    rejection_reason character varying(300),
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message (
    id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    sender_id uuid NOT NULL,
    body text NOT NULL,
    created_date timestamp with time zone NOT NULL,
    sender_identity character varying(10) NOT NULL,
    CONSTRAINT chk_message_sender_identity CHECK (((sender_identity)::text = ANY (ARRAY[('OWNER'::character varying)::text, ('BOARD'::character varying)::text])))
);


--
-- Name: message_draft; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message_draft (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    created_by uuid NOT NULL,
    is_broadcast boolean DEFAULT false NOT NULL,
    subject character varying(200),
    body text,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: message_draft_recipient; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message_draft_recipient (
    message_draft_id uuid NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    property_id uuid,
    type character varying(30) NOT NULL,
    title character varying(200) NOT NULL,
    body character varying(1000),
    link_path character varying(300),
    read_at timestamp with time zone,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY (ARRAY[('INSTALLMENT_OVERDUE'::character varying)::text, ('GENERAL_MEETING_CALLED'::character varying)::text, ('RELAUNCH_TO_VALIDATE'::character varying)::text, ('REQUEST_RECEIVED'::character varying)::text, ('GENERAL'::character varying)::text])))
);


--
-- Name: onboarding_lead; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.onboarding_lead (
    id uuid NOT NULL,
    email character varying(150) NOT NULL,
    first_name character varying(100),
    last_name character varying(100),
    converted_at timestamp with time zone,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: party; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.party (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    full_name character varying(200) NOT NULL,
    party_type character varying(20) NOT NULL,
    email character varying(150) NOT NULL,
    phone character varying(20),
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: party_invitation_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.party_invitation_token (
    id uuid NOT NULL,
    party_id uuid NOT NULL,
    email character varying(150) NOT NULL,
    full_name character varying(200) NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: password_reset_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_token (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    unit_id uuid NOT NULL,
    mode character varying(20) NOT NULL,
    value_date date NOT NULL,
    amount numeric(14,2) NOT NULL,
    journal_entry_id uuid NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    receipt_number character varying(20),
    CONSTRAINT payment_amount_check CHECK ((amount > (0)::numeric))
);


--
-- Name: period; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.period (
    id uuid NOT NULL,
    exercise_id uuid NOT NULL,
    year_month date NOT NULL,
    status character varying(20) NOT NULL,
    closed_at timestamp with time zone,
    closed_by_user_id uuid,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permission (
    key character varying(60) NOT NULL,
    description character varying(200) NOT NULL
);


--
-- Name: property; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    address character varying(250) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    dues_calculation_mode character varying(20) DEFAULT 'FLAT_RATE'::character varying NOT NULL,
    projected_budget numeric(12,2)
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_hash character varying(255) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked boolean DEFAULT false NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: refresh_token_authority; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token_authority (
    refresh_token_id uuid NOT NULL,
    authority character varying(50) NOT NULL
);


--
-- Name: reply_medium; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reply_medium (
    code character varying(30) NOT NULL,
    label character varying(100) NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: role_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permission (
    role_name character varying(50) NOT NULL,
    permission_key character varying(60) NOT NULL
);


--
-- Name: sequence_piece; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sequence_piece (
    property_id uuid NOT NULL,
    exercise_id uuid NOT NULL,
    journal_code character varying(4) NOT NULL,
    next_number integer DEFAULT 1 NOT NULL
);


--
-- Name: sequence_receipt; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sequence_receipt (
    property_id uuid NOT NULL,
    receipt_year integer NOT NULL,
    next_number integer DEFAULT 1 NOT NULL
);


--
-- Name: unit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit (
    id uuid NOT NULL,
    building_id uuid NOT NULL,
    property_id uuid NOT NULL,
    unit_number character varying(20) NOT NULL,
    unit_type_id uuid NOT NULL,
    shares numeric(12,2) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: unit_ownership; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit_ownership (
    id uuid NOT NULL,
    unit_id uuid NOT NULL,
    party_id uuid NOT NULL,
    property_id uuid NOT NULL,
    ownership_share numeric(5,2) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: unit_type_definition; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit_type_definition (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    name character varying(50) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: unit_type_pricing; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit_type_pricing (
    id uuid NOT NULL,
    property_id uuid NOT NULL,
    unit_type_id uuid NOT NULL,
    price numeric(12,2) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: user_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_role (
    user_id uuid NOT NULL,
    role character varying(50) NOT NULL
);


--
-- Name: verification_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_token (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: vote; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vote (
    id uuid NOT NULL,
    agenda_item_id uuid NOT NULL,
    unit_id uuid NOT NULL,
    choice character varying(20) NOT NULL,
    cast_at timestamp with time zone NOT NULL,
    cast_by_user_id uuid,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_vote_choice CHECK (((choice)::text = ANY ((ARRAY['FOR'::character varying, 'AGAINST'::character varying, 'ABSTENTION'::character varying])::text[])))
);


--
-- Name: accounting_exercise accounting_exercise_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_exercise
    ADD CONSTRAINT accounting_exercise_pkey PRIMARY KEY (id);


--
-- Name: allocation allocation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.allocation
    ADD CONSTRAINT allocation_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: board_member board_member_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_member
    ADD CONSTRAINT board_member_pkey PRIMARY KEY (id);


--
-- Name: building building_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building
    ADD CONSTRAINT building_pkey PRIMARY KEY (id);


--
-- Name: conversation conversation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation
    ADD CONSTRAINT conversation_pkey PRIMARY KEY (id);


--
-- Name: device_push_token device_push_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_push_token
    ADD CONSTRAINT device_push_token_pkey PRIMARY KEY (id);


--
-- Name: document document_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_pkey PRIMARY KEY (id);


--
-- Name: expense expense_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense
    ADD CONSTRAINT expense_pkey PRIMARY KEY (id);


--
-- Name: installment_call installment_call_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.installment_call
    ADD CONSTRAINT installment_call_pkey PRIMARY KEY (id);


--
-- Name: installment installment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.installment
    ADD CONSTRAINT installment_pkey PRIMARY KEY (id);


--
-- Name: invitation invitation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitation
    ADD CONSTRAINT invitation_pkey PRIMARY KEY (id);


--
-- Name: journal_entry_line journal_entry_line_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entry_line
    ADD CONSTRAINT journal_entry_line_pkey PRIMARY KEY (id);


--
-- Name: journal_entry journal_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entry
    ADD CONSTRAINT journal_entry_pkey PRIMARY KEY (id);


--
-- Name: journal journal_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal
    ADD CONSTRAINT journal_pkey PRIMARY KEY (code);


--
-- Name: ledger_account_number_sequence ledger_account_number_sequence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ledger_account_number_sequence
    ADD CONSTRAINT ledger_account_number_sequence_pkey PRIMARY KEY (property_id, number_prefix);


--
-- Name: ledger_account ledger_account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ledger_account
    ADD CONSTRAINT ledger_account_pkey PRIMARY KEY (id);


--
-- Name: membership_request membership_request_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_request
    ADD CONSTRAINT membership_request_pkey PRIMARY KEY (id);


--
-- Name: message_draft message_draft_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_draft
    ADD CONSTRAINT message_draft_pkey PRIMARY KEY (id);


--
-- Name: message message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: onboarding_lead onboarding_lead_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.onboarding_lead
    ADD CONSTRAINT onboarding_lead_pkey PRIMARY KEY (id);


--
-- Name: party_invitation_token party_invitation_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.party_invitation_token
    ADD CONSTRAINT party_invitation_token_pkey PRIMARY KEY (id);


--
-- Name: party party_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.party
    ADD CONSTRAINT party_pkey PRIMARY KEY (id);


--
-- Name: password_reset_token password_reset_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT password_reset_token_pkey PRIMARY KEY (id);


--
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);


--
-- Name: period period_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.period
    ADD CONSTRAINT period_pkey PRIMARY KEY (id);


--
-- Name: permission permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (key);


--
-- Name: agenda_item pk_agenda_item; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_item
    ADD CONSTRAINT pk_agenda_item PRIMARY KEY (id);


--
-- Name: app_user_party pk_app_user_party; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user_party
    ADD CONSTRAINT pk_app_user_party PRIMARY KEY (app_user_id, party_id);


--
-- Name: app_user_party_role pk_app_user_party_role; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user_party_role
    ADD CONSTRAINT pk_app_user_party_role PRIMARY KEY (app_user_id, party_id, role);


--
-- Name: conversation_participant pk_conversation_participant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_participant
    ADD CONSTRAINT pk_conversation_participant PRIMARY KEY (conversation_id, user_id);


--
-- Name: conversation_read_marker pk_conversation_read_marker; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_read_marker
    ADD CONSTRAINT pk_conversation_read_marker PRIMARY KEY (conversation_id, user_id);


--
-- Name: convocation pk_convocation; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation
    ADD CONSTRAINT pk_convocation PRIMARY KEY (id);


--
-- Name: convocation_channel pk_convocation_channel; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation_channel
    ADD CONSTRAINT pk_convocation_channel PRIMARY KEY (code);


--
-- Name: convocation_delivery pk_convocation_delivery; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation_delivery
    ADD CONSTRAINT pk_convocation_delivery PRIMARY KEY (id);


--
-- Name: convocation_reply pk_convocation_reply; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation_reply
    ADD CONSTRAINT pk_convocation_reply PRIMARY KEY (id);


--
-- Name: general_meeting pk_general_meeting; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.general_meeting
    ADD CONSTRAINT pk_general_meeting PRIMARY KEY (id);


--
-- Name: meeting_minutes pk_meeting_minutes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_minutes
    ADD CONSTRAINT pk_meeting_minutes PRIMARY KEY (id);


--
-- Name: meeting_quorum_setting pk_meeting_quorum_setting; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_quorum_setting
    ADD CONSTRAINT pk_meeting_quorum_setting PRIMARY KEY (id);


--
-- Name: message_draft_recipient pk_message_draft_recipient; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_draft_recipient
    ADD CONSTRAINT pk_message_draft_recipient PRIMARY KEY (message_draft_id, user_id);


--
-- Name: refresh_token_authority pk_refresh_token_authority; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token_authority
    ADD CONSTRAINT pk_refresh_token_authority PRIMARY KEY (refresh_token_id, authority);


--
-- Name: reply_medium pk_reply_medium; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reply_medium
    ADD CONSTRAINT pk_reply_medium PRIMARY KEY (code);


--
-- Name: role_permission pk_role_permission; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT pk_role_permission PRIMARY KEY (role_name, permission_key);


--
-- Name: sequence_receipt pk_sequence_receipt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sequence_receipt
    ADD CONSTRAINT pk_sequence_receipt PRIMARY KEY (property_id, receipt_year);


--
-- Name: user_role pk_user_role; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT pk_user_role PRIMARY KEY (user_id, role);


--
-- Name: vote pk_vote; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote
    ADD CONSTRAINT pk_vote PRIMARY KEY (id);


--
-- Name: property property_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property
    ADD CONSTRAINT property_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: sequence_piece sequence_piece_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sequence_piece
    ADD CONSTRAINT sequence_piece_pkey PRIMARY KEY (property_id, exercise_id, journal_code);


--
-- Name: agenda_item uk_agenda_item_position; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_item
    ADD CONSTRAINT uk_agenda_item_position UNIQUE (general_meeting_id, "position") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_user uk_app_user_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk_app_user_email UNIQUE (email);


--
-- Name: app_user_party uk_app_user_party_party; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user_party
    ADD CONSTRAINT uk_app_user_party_party UNIQUE (party_id);


--
-- Name: board_member uk_board_member_property_party_role; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_member
    ADD CONSTRAINT uk_board_member_property_party_role UNIQUE (property_id, party_id, board_role);


--
-- Name: convocation uk_convocation_confirmation_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation
    ADD CONSTRAINT uk_convocation_confirmation_token UNIQUE (confirmation_token);


--
-- Name: convocation uk_convocation_meeting_confirmation_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation
    ADD CONSTRAINT uk_convocation_meeting_confirmation_code UNIQUE (general_meeting_id, confirmation_code);


--
-- Name: convocation uk_convocation_meeting_unit; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation
    ADD CONSTRAINT uk_convocation_meeting_unit UNIQUE (general_meeting_id, unit_id);


--
-- Name: device_push_token uk_device_push_token_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_push_token
    ADD CONSTRAINT uk_device_push_token_token UNIQUE (expo_push_token);


--
-- Name: general_meeting uk_general_meeting_public_reference; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.general_meeting
    ADD CONSTRAINT uk_general_meeting_public_reference UNIQUE (public_reference);


--
-- Name: installment_call uk_installment_call_property_period; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.installment_call
    ADD CONSTRAINT uk_installment_call_property_period UNIQUE (property_id, period);


--
-- Name: invitation uk_invitation_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitation
    ADD CONSTRAINT uk_invitation_token UNIQUE (token);


--
-- Name: meeting_minutes uk_meeting_minutes_general_meeting; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_minutes
    ADD CONSTRAINT uk_meeting_minutes_general_meeting UNIQUE (general_meeting_id);


--
-- Name: meeting_quorum_setting uk_meeting_quorum_setting_property_type; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_quorum_setting
    ADD CONSTRAINT uk_meeting_quorum_setting_property_type UNIQUE (property_id, meeting_type);


--
-- Name: onboarding_lead uk_onboarding_lead_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.onboarding_lead
    ADD CONSTRAINT uk_onboarding_lead_email UNIQUE (email);


--
-- Name: party uk_party_id_property; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.party
    ADD CONSTRAINT uk_party_id_property UNIQUE (id, property_id);


--
-- Name: party_invitation_token uk_party_invitation_token_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.party_invitation_token
    ADD CONSTRAINT uk_party_invitation_token_token UNIQUE (token);


--
-- Name: party uk_party_property_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.party
    ADD CONSTRAINT uk_party_property_email UNIQUE (property_id, email);


--
-- Name: password_reset_token uk_password_reset_token_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT uk_password_reset_token_token UNIQUE (token);


--
-- Name: refresh_token uk_refresh_token_token_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT uk_refresh_token_token_hash UNIQUE (token_hash);


--
-- Name: unit uk_unit_id_property; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT uk_unit_id_property UNIQUE (id, property_id);


--
-- Name: unit_ownership uk_unit_ownership_unit_party; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_ownership
    ADD CONSTRAINT uk_unit_ownership_unit_party UNIQUE (unit_id, party_id);


--
-- Name: unit_type_definition uk_unit_type_definition_property_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_type_definition
    ADD CONSTRAINT uk_unit_type_definition_property_name UNIQUE (property_id, name);


--
-- Name: unit_type_pricing uk_unit_type_pricing_unit_type; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_type_pricing
    ADD CONSTRAINT uk_unit_type_pricing_unit_type UNIQUE (unit_type_id);


--
-- Name: verification_token uk_verification_token_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT uk_verification_token_token UNIQUE (token);


--
-- Name: vote uk_vote_agenda_item_unit; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote
    ADD CONSTRAINT uk_vote_agenda_item_unit UNIQUE (agenda_item_id, unit_id);


--
-- Name: unit_ownership unit_ownership_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_ownership
    ADD CONSTRAINT unit_ownership_pkey PRIMARY KEY (id);


--
-- Name: unit unit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT unit_pkey PRIMARY KEY (id);


--
-- Name: unit_type_definition unit_type_definition_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_type_definition
    ADD CONSTRAINT unit_type_definition_pkey PRIMARY KEY (id);


--
-- Name: unit_type_pricing unit_type_pricing_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_type_pricing
    ADD CONSTRAINT unit_type_pricing_pkey PRIMARY KEY (id);


--
-- Name: verification_token verification_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT verification_token_pkey PRIMARY KEY (id);


--
-- Name: idx_accounting_exercise_property_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_accounting_exercise_property_id ON public.accounting_exercise USING btree (property_id);


--
-- Name: idx_allocation_credit_line; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_allocation_credit_line ON public.allocation USING btree (credit_line_id);


--
-- Name: idx_allocation_debit_line; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_allocation_debit_line ON public.allocation USING btree (debit_line_id);


--
-- Name: idx_app_user_party_role_property_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_app_user_party_role_property_id ON public.app_user_party_role USING btree (property_id);


--
-- Name: idx_board_member_party_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_board_member_party_id ON public.board_member USING btree (party_id);


--
-- Name: idx_board_member_property_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_board_member_property_id ON public.board_member USING btree (property_id);


--
-- Name: idx_building_property_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_building_property_id ON public.building USING btree (property_id);


--
-- Name: idx_conversation_participant_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_conversation_participant_user ON public.conversation_participant USING btree (user_id);


--
-- Name: idx_conversation_property; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_conversation_property ON public.conversation USING btree (property_id);


--
-- Name: idx_convocation_delivery_convocation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_convocation_delivery_convocation ON public.convocation_delivery USING btree (convocation_id);


--
-- Name: idx_convocation_reply_convocation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_convocation_reply_convocation ON public.convocation_reply USING btree (convocation_id, received_at DESC);


--
-- Name: idx_convocation_unit; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_convocation_unit ON public.convocation USING btree (unit_id);


--
-- Name: idx_device_push_token_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_device_push_token_user_id ON public.device_push_token USING btree (user_id);


--
-- Name: idx_document_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_owner ON public.document USING btree (owner_type, owner_id);


--
-- Name: idx_expense_property_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_expense_property_id ON public.expense USING btree (property_id);


--
-- Name: idx_general_meeting_property; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_general_meeting_property ON public.general_meeting USING btree (property_id, scheduled_at);


--
-- Name: idx_installment_installment_call_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_installment_installment_call_id ON public.installment USING btree (installment_call_id);


--
-- Name: idx_installment_unit_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_installment_unit_id ON public.installment USING btree (unit_id);


--
-- Name: idx_invitation_property_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invitation_property_status ON public.invitation USING btree (property_id, status);


--
-- Name: idx_journal_entry_line_account_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_journal_entry_line_account_id ON public.journal_entry_line USING btree (ledger_account_id);


--
-- Name: idx_journal_entry_line_auxiliary_party; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_journal_entry_line_auxiliary_party ON public.journal_entry_line USING btree (auxiliary_party_id);


--
-- Name: idx_journal_entry_line_auxiliary_unit; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_journal_entry_line_auxiliary_unit ON public.journal_entry_line USING btree (auxiliary_unit_id);


--
-- Name: idx_journal_entry_line_entry_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_journal_entry_line_entry_id ON public.journal_entry_line USING btree (journal_entry_id);


--
-- Name: idx_journal_entry_original_entry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_journal_entry_original_entry ON public.journal_entry USING btree (original_entry_id);


--
-- Name: idx_journal_entry_property_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_journal_entry_property_date ON public.journal_entry USING btree (property_id, piece_date);


--
-- Name: idx_ledger_account_property_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ledger_account_property_role ON public.ledger_account USING btree (property_id, role);


--
-- Name: idx_ledger_account_unit_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ledger_account_unit_id ON public.ledger_account USING btree (unit_id);


--
-- Name: idx_membership_request_property_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_request_property_status ON public.membership_request USING btree (property_id, status);


--
-- Name: idx_membership_request_unit_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_request_unit_status ON public.membership_request USING btree (unit_id, status);


--
-- Name: idx_message_conversation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_message_conversation ON public.message USING btree (conversation_id, created_date);


--
-- Name: idx_message_draft_created_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_message_draft_created_by ON public.message_draft USING btree (created_by);


--
-- Name: idx_notification_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notification_user_created ON public.notification USING btree (user_id, created_date DESC);


--
-- Name: idx_notification_user_unread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notification_user_unread ON public.notification USING btree (user_id) WHERE (read_at IS NULL);


--
-- Name: idx_onboarding_lead_converted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_onboarding_lead_converted_at ON public.onboarding_lead USING btree (converted_at);


--
-- Name: idx_party_invitation_token_party_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_party_invitation_token_party_id ON public.party_invitation_token USING btree (party_id);


--
-- Name: idx_party_property_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_party_property_id ON public.party USING btree (property_id);


--
-- Name: idx_password_reset_token_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_password_reset_token_user_id ON public.password_reset_token USING btree (user_id);


--
-- Name: idx_payment_property_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payment_property_id ON public.payment USING btree (property_id);


--
-- Name: idx_payment_unit_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payment_unit_id ON public.payment USING btree (unit_id);


--
-- Name: idx_refresh_token_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_token_user_id ON public.refresh_token USING btree (user_id);


--
-- Name: idx_unit_building_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_unit_building_id ON public.unit USING btree (building_id);


--
-- Name: idx_unit_ownership_party_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_unit_ownership_party_id ON public.unit_ownership USING btree (party_id);


--
-- Name: idx_unit_ownership_property_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_unit_ownership_property_id ON public.unit_ownership USING btree (property_id);


--
-- Name: idx_unit_ownership_unit_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_unit_ownership_unit_id ON public.unit_ownership USING btree (unit_id);


--
-- Name: idx_unit_property_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_unit_property_id ON public.unit USING btree (property_id);


--
-- Name: idx_unit_type_definition_property_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_unit_type_definition_property_id ON public.unit_type_definition USING btree (property_id);


--
-- Name: idx_unit_type_pricing_property_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_unit_type_pricing_property_id ON public.unit_type_pricing USING btree (property_id);


--
-- Name: idx_unit_type_pricing_unit_type_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_unit_type_pricing_unit_type_id ON public.unit_type_pricing USING btree (unit_type_id);


--
-- Name: idx_unit_unit_type_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_unit_unit_type_id ON public.unit USING btree (unit_type_id);


--
-- Name: idx_verification_token_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_verification_token_user_id ON public.verification_token USING btree (user_id);


--
-- Name: uk_accounting_exercise_property_open; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_accounting_exercise_property_open ON public.accounting_exercise USING btree (property_id) WHERE ((status)::text = 'OPEN'::text);


--
-- Name: uk_conversation_broadcast_property; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_conversation_broadcast_property ON public.conversation USING btree (property_id) WHERE ((type)::text = 'BROADCAST'::text);


--
-- Name: uk_document_owner_checksum; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_document_owner_checksum ON public.document USING btree (owner_type, owner_id, checksum_sha256);


--
-- Name: uk_journal_entry_piece; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_journal_entry_piece ON public.journal_entry USING btree (property_id, exercise_id, journal_code, piece_number) WHERE (piece_number IS NOT NULL);


--
-- Name: uk_ledger_account_global_number; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_ledger_account_global_number ON public.ledger_account USING btree (account_number) WHERE (property_id IS NULL);


--
-- Name: uk_ledger_account_scoped_number; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_ledger_account_scoped_number ON public.ledger_account USING btree (property_id, account_number) WHERE (property_id IS NOT NULL);


--
-- Name: uk_party_property_phone; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_party_property_phone ON public.party USING btree (property_id, phone) WHERE (phone IS NOT NULL);


--
-- Name: uk_period_exercise_year_month; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_period_exercise_year_month ON public.period USING btree (exercise_id, year_month);


--
-- Name: journal_entry trg_journal_entry_immutable; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_journal_entry_immutable BEFORE DELETE OR UPDATE ON public.journal_entry FOR EACH ROW EXECUTE FUNCTION public.reject_journal_entry_mutation();


--
-- Name: journal_entry_line trg_journal_entry_line_immutable; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_journal_entry_line_immutable BEFORE INSERT OR DELETE OR UPDATE ON public.journal_entry_line FOR EACH ROW EXECUTE FUNCTION public.reject_journal_entry_line_mutation_when_not_draft();


--
-- Name: accounting_exercise accounting_exercise_property_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_exercise
    ADD CONSTRAINT accounting_exercise_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Name: allocation allocation_credit_line_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.allocation
    ADD CONSTRAINT allocation_credit_line_id_fkey FOREIGN KEY (credit_line_id) REFERENCES public.journal_entry_line(id);


--
-- Name: allocation allocation_debit_line_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.allocation
    ADD CONSTRAINT allocation_debit_line_id_fkey FOREIGN KEY (debit_line_id) REFERENCES public.journal_entry_line(id);


--
-- Name: conversation conversation_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation
    ADD CONSTRAINT conversation_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_user(id);


--
-- Name: conversation_participant conversation_participant_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_participant
    ADD CONSTRAINT conversation_participant_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversation(id) ON DELETE CASCADE;


--
-- Name: conversation_participant conversation_participant_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_participant
    ADD CONSTRAINT conversation_participant_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: conversation conversation_property_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation
    ADD CONSTRAINT conversation_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.property(id) ON DELETE CASCADE;


--
-- Name: conversation_read_marker conversation_read_marker_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_read_marker
    ADD CONSTRAINT conversation_read_marker_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversation(id) ON DELETE CASCADE;


--
-- Name: conversation_read_marker conversation_read_marker_last_read_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_read_marker
    ADD CONSTRAINT conversation_read_marker_last_read_message_id_fkey FOREIGN KEY (last_read_message_id) REFERENCES public.message(id);


--
-- Name: conversation_read_marker conversation_read_marker_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_read_marker
    ADD CONSTRAINT conversation_read_marker_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: device_push_token device_push_token_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_push_token
    ADD CONSTRAINT device_push_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: document document_uploaded_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.app_user(id);


--
-- Name: expense expense_journal_entry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense
    ADD CONSTRAINT expense_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entry(id);


--
-- Name: expense expense_ledger_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense
    ADD CONSTRAINT expense_ledger_account_id_fkey FOREIGN KEY (ledger_account_id) REFERENCES public.ledger_account(id);


--
-- Name: expense expense_property_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense
    ADD CONSTRAINT expense_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Name: agenda_item fk_agenda_item_general_meeting; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_item
    ADD CONSTRAINT fk_agenda_item_general_meeting FOREIGN KEY (general_meeting_id) REFERENCES public.general_meeting(id) ON DELETE CASCADE;


--
-- Name: app_user_party fk_app_user_party_party; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user_party
    ADD CONSTRAINT fk_app_user_party_party FOREIGN KEY (party_id) REFERENCES public.party(id) ON DELETE CASCADE;


--
-- Name: app_user_party_role fk_app_user_party_role_party_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user_party_role
    ADD CONSTRAINT fk_app_user_party_role_party_property FOREIGN KEY (party_id, property_id) REFERENCES public.party(id, property_id) ON DELETE CASCADE;


--
-- Name: app_user_party_role fk_app_user_party_role_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user_party_role
    ADD CONSTRAINT fk_app_user_party_role_user FOREIGN KEY (app_user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: app_user_party fk_app_user_party_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user_party
    ADD CONSTRAINT fk_app_user_party_user FOREIGN KEY (app_user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: board_member fk_board_member_party_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_member
    ADD CONSTRAINT fk_board_member_party_property FOREIGN KEY (party_id, property_id) REFERENCES public.party(id, property_id);


--
-- Name: board_member fk_board_member_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_member
    ADD CONSTRAINT fk_board_member_property FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Name: building fk_building_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building
    ADD CONSTRAINT fk_building_property FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Name: convocation fk_convocation_checked_in_party; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation
    ADD CONSTRAINT fk_convocation_checked_in_party FOREIGN KEY (checked_in_party_id) REFERENCES public.party(id);


--
-- Name: convocation_delivery fk_convocation_delivery_channel; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation_delivery
    ADD CONSTRAINT fk_convocation_delivery_channel FOREIGN KEY (channel_code) REFERENCES public.convocation_channel(code);


--
-- Name: convocation_delivery fk_convocation_delivery_convocation; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation_delivery
    ADD CONSTRAINT fk_convocation_delivery_convocation FOREIGN KEY (convocation_id) REFERENCES public.convocation(id) ON DELETE CASCADE;


--
-- Name: convocation fk_convocation_general_meeting; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation
    ADD CONSTRAINT fk_convocation_general_meeting FOREIGN KEY (general_meeting_id) REFERENCES public.general_meeting(id) ON DELETE CASCADE;


--
-- Name: convocation fk_convocation_replied_by_party; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation
    ADD CONSTRAINT fk_convocation_replied_by_party FOREIGN KEY (replied_by_party_id) REFERENCES public.party(id);


--
-- Name: convocation_reply fk_convocation_reply_convocation; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation_reply
    ADD CONSTRAINT fk_convocation_reply_convocation FOREIGN KEY (convocation_id) REFERENCES public.convocation(id) ON DELETE CASCADE;


--
-- Name: convocation fk_convocation_reply_medium; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation
    ADD CONSTRAINT fk_convocation_reply_medium FOREIGN KEY (reply_medium) REFERENCES public.reply_medium(code);


--
-- Name: convocation_reply fk_convocation_reply_medium; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation_reply
    ADD CONSTRAINT fk_convocation_reply_medium FOREIGN KEY (reply_medium) REFERENCES public.reply_medium(code);


--
-- Name: convocation_reply fk_convocation_reply_party; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation_reply
    ADD CONSTRAINT fk_convocation_reply_party FOREIGN KEY (replied_by_party_id) REFERENCES public.party(id);


--
-- Name: convocation fk_convocation_unit; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.convocation
    ADD CONSTRAINT fk_convocation_unit FOREIGN KEY (unit_id) REFERENCES public.unit(id);


--
-- Name: general_meeting fk_general_meeting_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.general_meeting
    ADD CONSTRAINT fk_general_meeting_property FOREIGN KEY (property_id) REFERENCES public.property(id) ON DELETE CASCADE;


--
-- Name: installment fk_installment_installment_call; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.installment
    ADD CONSTRAINT fk_installment_installment_call FOREIGN KEY (installment_call_id) REFERENCES public.installment_call(id);


--
-- Name: installment fk_installment_unit; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.installment
    ADD CONSTRAINT fk_installment_unit FOREIGN KEY (unit_id) REFERENCES public.unit(id);


--
-- Name: invitation fk_invitation_created_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitation
    ADD CONSTRAINT fk_invitation_created_by FOREIGN KEY (created_by_user_id) REFERENCES public.app_user(id);


--
-- Name: invitation fk_invitation_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitation
    ADD CONSTRAINT fk_invitation_property FOREIGN KEY (property_id) REFERENCES public.property(id) ON DELETE CASCADE;


--
-- Name: meeting_minutes fk_meeting_minutes_general_meeting; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_minutes
    ADD CONSTRAINT fk_meeting_minutes_general_meeting FOREIGN KEY (general_meeting_id) REFERENCES public.general_meeting(id) ON DELETE CASCADE;


--
-- Name: meeting_quorum_setting fk_meeting_quorum_setting_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_quorum_setting
    ADD CONSTRAINT fk_meeting_quorum_setting_property FOREIGN KEY (property_id) REFERENCES public.property(id) ON DELETE CASCADE;


--
-- Name: membership_request fk_membership_request_decided_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_request
    ADD CONSTRAINT fk_membership_request_decided_by FOREIGN KEY (decided_by_user_id) REFERENCES public.app_user(id);


--
-- Name: membership_request fk_membership_request_invitation; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_request
    ADD CONSTRAINT fk_membership_request_invitation FOREIGN KEY (invitation_id) REFERENCES public.invitation(id) ON DELETE CASCADE;


--
-- Name: membership_request fk_membership_request_unit; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_request
    ADD CONSTRAINT fk_membership_request_unit FOREIGN KEY (unit_id) REFERENCES public.unit(id) ON DELETE CASCADE;


--
-- Name: membership_request fk_membership_request_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_request
    ADD CONSTRAINT fk_membership_request_user FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: party_invitation_token fk_party_invitation_token_party; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.party_invitation_token
    ADD CONSTRAINT fk_party_invitation_token_party FOREIGN KEY (party_id) REFERENCES public.party(id) ON DELETE CASCADE;


--
-- Name: party fk_party_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.party
    ADD CONSTRAINT fk_party_property FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Name: password_reset_token fk_password_reset_token_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT fk_password_reset_token_user FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: refresh_token_authority fk_refresh_token_authority_token; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token_authority
    ADD CONSTRAINT fk_refresh_token_authority_token FOREIGN KEY (refresh_token_id) REFERENCES public.refresh_token(id) ON DELETE CASCADE;


--
-- Name: role_permission fk_role_permission_permission; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_key) REFERENCES public.permission(key);


--
-- Name: unit fk_unit_building; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT fk_unit_building FOREIGN KEY (building_id) REFERENCES public.building(id);


--
-- Name: unit_ownership fk_unit_ownership_party_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_ownership
    ADD CONSTRAINT fk_unit_ownership_party_property FOREIGN KEY (party_id, property_id) REFERENCES public.party(id, property_id);


--
-- Name: unit_ownership fk_unit_ownership_unit_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_ownership
    ADD CONSTRAINT fk_unit_ownership_unit_property FOREIGN KEY (unit_id, property_id) REFERENCES public.unit(id, property_id);


--
-- Name: unit fk_unit_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT fk_unit_property FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Name: unit_type_definition fk_unit_type_definition_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_type_definition
    ADD CONSTRAINT fk_unit_type_definition_property FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Name: unit_type_pricing fk_unit_type_pricing_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_type_pricing
    ADD CONSTRAINT fk_unit_type_pricing_property FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Name: unit_type_pricing fk_unit_type_pricing_unit_type; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_type_pricing
    ADD CONSTRAINT fk_unit_type_pricing_unit_type FOREIGN KEY (unit_type_id) REFERENCES public.unit_type_definition(id) ON DELETE CASCADE;


--
-- Name: unit fk_unit_unit_type; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT fk_unit_unit_type FOREIGN KEY (unit_type_id) REFERENCES public.unit_type_definition(id);


--
-- Name: user_role fk_user_role_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: verification_token fk_verification_token_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT fk_verification_token_user FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: vote fk_vote_agenda_item; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote
    ADD CONSTRAINT fk_vote_agenda_item FOREIGN KEY (agenda_item_id) REFERENCES public.agenda_item(id) ON DELETE CASCADE;


--
-- Name: vote fk_vote_cast_by_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote
    ADD CONSTRAINT fk_vote_cast_by_user FOREIGN KEY (cast_by_user_id) REFERENCES public.app_user(id);


--
-- Name: vote fk_vote_unit; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote
    ADD CONSTRAINT fk_vote_unit FOREIGN KEY (unit_id) REFERENCES public.unit(id);


--
-- Name: installment_call installment_call_journal_entry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.installment_call
    ADD CONSTRAINT installment_call_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entry(id);


--
-- Name: installment installment_journal_entry_line_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.installment
    ADD CONSTRAINT installment_journal_entry_line_id_fkey FOREIGN KEY (journal_entry_line_id) REFERENCES public.journal_entry_line(id);


--
-- Name: journal_entry journal_entry_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entry
    ADD CONSTRAINT journal_entry_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.accounting_exercise(id);


--
-- Name: journal_entry journal_entry_journal_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entry
    ADD CONSTRAINT journal_entry_journal_code_fkey FOREIGN KEY (journal_code) REFERENCES public.journal(code);


--
-- Name: journal_entry_line journal_entry_line_auxiliary_party_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entry_line
    ADD CONSTRAINT journal_entry_line_auxiliary_party_id_fkey FOREIGN KEY (auxiliary_party_id) REFERENCES public.party(id);


--
-- Name: journal_entry_line journal_entry_line_auxiliary_unit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entry_line
    ADD CONSTRAINT journal_entry_line_auxiliary_unit_id_fkey FOREIGN KEY (auxiliary_unit_id) REFERENCES public.unit(id);


--
-- Name: journal_entry_line journal_entry_line_journal_entry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entry_line
    ADD CONSTRAINT journal_entry_line_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entry(id);


--
-- Name: journal_entry_line journal_entry_line_ledger_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entry_line
    ADD CONSTRAINT journal_entry_line_ledger_account_id_fkey FOREIGN KEY (ledger_account_id) REFERENCES public.ledger_account(id);


--
-- Name: journal_entry journal_entry_original_entry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entry
    ADD CONSTRAINT journal_entry_original_entry_id_fkey FOREIGN KEY (original_entry_id) REFERENCES public.journal_entry(id);


--
-- Name: journal_entry journal_entry_period_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entry
    ADD CONSTRAINT journal_entry_period_id_fkey FOREIGN KEY (period_id) REFERENCES public.period(id);


--
-- Name: journal_entry journal_entry_property_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entry
    ADD CONSTRAINT journal_entry_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Name: journal_entry journal_entry_treasury_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entry
    ADD CONSTRAINT journal_entry_treasury_account_id_fkey FOREIGN KEY (treasury_account_id) REFERENCES public.ledger_account(id);


--
-- Name: ledger_account_number_sequence ledger_account_number_sequence_property_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ledger_account_number_sequence
    ADD CONSTRAINT ledger_account_number_sequence_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Name: ledger_account ledger_account_property_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ledger_account
    ADD CONSTRAINT ledger_account_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Name: ledger_account ledger_account_unit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ledger_account
    ADD CONSTRAINT ledger_account_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.unit(id);


--
-- Name: message message_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversation(id) ON DELETE CASCADE;


--
-- Name: message_draft message_draft_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_draft
    ADD CONSTRAINT message_draft_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_user(id);


--
-- Name: message_draft message_draft_property_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_draft
    ADD CONSTRAINT message_draft_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.property(id) ON DELETE CASCADE;


--
-- Name: message_draft_recipient message_draft_recipient_message_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_draft_recipient
    ADD CONSTRAINT message_draft_recipient_message_draft_id_fkey FOREIGN KEY (message_draft_id) REFERENCES public.message_draft(id) ON DELETE CASCADE;


--
-- Name: message_draft_recipient message_draft_recipient_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_draft_recipient
    ADD CONSTRAINT message_draft_recipient_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: message message_sender_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.app_user(id);


--
-- Name: notification notification_property_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.property(id) ON DELETE CASCADE;


--
-- Name: notification notification_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: payment payment_journal_entry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entry(id);


--
-- Name: payment payment_property_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Name: payment payment_unit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.unit(id);


--
-- Name: period period_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.period
    ADD CONSTRAINT period_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.accounting_exercise(id);


--
-- Name: sequence_piece sequence_piece_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sequence_piece
    ADD CONSTRAINT sequence_piece_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.accounting_exercise(id);


--
-- Name: sequence_piece sequence_piece_journal_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sequence_piece
    ADD CONSTRAINT sequence_piece_journal_code_fkey FOREIGN KEY (journal_code) REFERENCES public.journal(code);


--
-- Name: sequence_piece sequence_piece_property_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sequence_piece
    ADD CONSTRAINT sequence_piece_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Reference-table seed data.
--
-- Folded in rather than left to their own migrations because a schema-only
-- squash loses them silently - which has now happened to this file twice, and
-- was very nearly a third time: `pg_dump --schema-only` captured none of these
-- rows, and the `meeting:*` permissions that V4 introduced went missing until
-- RolePermissionSeedTest caught it. Every block below is dumped from the
-- database the 15 migrations actually produced, not retyped from the files.
--

-- permission: the closed catalog role_permission.permission_key FKs to (see Permission.java).
INSERT INTO permission (key, description) VALUES
    ('document:read', 'Read documents'),
    ('document:write', 'Upload or delete documents'),
    ('installment:call:write', 'Create or update an installment call'),
    ('installment:read', 'Read installments and installment calls'),
    ('invitation:manage', 'Manage a property''s invitations and membership requests'),
    ('meeting:manage', 'Create and run a property''s general meetings'),
    ('meeting:minutes:publish', 'Validate and publish a general meeting''s minutes'),
    ('meeting:read', 'Read a property''s general meetings'),
    ('messaging:broadcast', 'Post to a property''s broadcast announcement channel'),
    ('party:invite', 'Invite a party onto a property'),
    ('party:read', 'Read a party''s details'),
    ('party:write', 'Create or update a party'),
    ('property:accounting:read', 'Read a property''s accounting module'),
    ('property:accounting:write', 'Write to a property''s accounting module'),
    ('property:board:manage', 'Manage a property''s board members'),
    ('property:create', 'Create a new property'),
    ('property:member:invite', 'Invite a member onto a property'),
    ('property:read', 'Read a property''s details'),
    ('property:update', 'Update a property''s details'),
    ('unit:ownership:write', 'Create or update a unit''s ownership'),
    ('unit:read', 'Read a unit''s details'),
    ('unit:write', 'Create or update a unit'),
    ('user:admin', 'Administer user accounts');

-- journal: the 6 fixed journals of spec §3.3 that journal_entry/sequence_piece.journal_code FK to (see JournalCode.java).
INSERT INTO journal (code, label, type, treasury_role, postable) VALUES
    ('AC', 'Achats', 'PURCHASES', NULL, true),
    ('AN', 'A-nouveaux', 'OPENING', NULL, false),
    ('BQ', 'Banque', 'TREASURY', 'BANK', true),
    ('CA', 'Caisse', 'TREASURY', 'CASH', true),
    ('OD', 'Operations diverses', 'MISCELLANEOUS', NULL, true),
    ('VT', 'Ventes / Appels de fonds', 'SALES', NULL, true);

-- convocation_channel: the ways a convocation can go out (see ConvocationChannel.java).
-- `automated` is the distinction that carries a consequence: the application performs those
-- itself, the others are recorded once a person has acted. An automated row with no emitter
-- behind it promises a send that never happens - ConvocationChannelLookup refuses it.
INSERT INTO convocation_channel (code, label, automated, position, active) VALUES
    ('EMAIL', 'Email', true, 1, true),
    ('APP', 'Messagerie interne', true, 2, true),
    ('POSTAL_MAIL', 'Courrier', false, 3, true),
    ('REGISTERED_MAIL', 'Courrier recommandé avec AR', false, 4, true),
    ('MANUAL', 'Remise en main propre', false, 5, true);

-- reply_medium: by what means an answer reaches the office (see ReplyMediumCode.java).
-- No `automated` counterpart to the channels': nothing is ever emitted through a medium.
INSERT INTO reply_medium (code, label, position, active) VALUES
    ('TELEPHONE', 'Téléphone', 1, true),
    ('COURRIER', 'Courrier', 2, true),
    ('EMAIL', 'Email', 3, true),
    ('GUICHET', 'Au bureau', 4, true);

-- role_permission: the role -> permission bundles GetUserAccessService resolves every
-- authorization from. Without these rows every @PreAuthorize that checks a Permission denies -
-- a database provisioned by Flyway alone would authenticate fine and authorize nothing.
INSERT INTO role_permission (role_name, permission_key) VALUES
    ('PROPERTY_BOARD_ADMIN', 'document:read'),
    ('PROPERTY_BOARD_ADMIN', 'document:write'),
    ('PROPERTY_BOARD_ADMIN', 'installment:call:write'),
    ('PROPERTY_BOARD_ADMIN', 'installment:read'),
    ('PROPERTY_BOARD_ADMIN', 'invitation:manage'),
    ('PROPERTY_BOARD_ADMIN', 'meeting:manage'),
    ('PROPERTY_BOARD_ADMIN', 'meeting:minutes:publish'),
    ('PROPERTY_BOARD_ADMIN', 'meeting:read'),
    ('PROPERTY_BOARD_ADMIN', 'messaging:broadcast'),
    ('PROPERTY_BOARD_ADMIN', 'party:invite'),
    ('PROPERTY_BOARD_ADMIN', 'party:read'),
    ('PROPERTY_BOARD_ADMIN', 'party:write'),
    ('PROPERTY_BOARD_ADMIN', 'property:accounting:read'),
    ('PROPERTY_BOARD_ADMIN', 'property:accounting:write'),
    ('PROPERTY_BOARD_ADMIN', 'property:board:manage'),
    ('PROPERTY_BOARD_ADMIN', 'property:create'),
    ('PROPERTY_BOARD_ADMIN', 'property:member:invite'),
    ('PROPERTY_BOARD_ADMIN', 'property:read'),
    ('PROPERTY_BOARD_ADMIN', 'property:update'),
    ('PROPERTY_BOARD_ADMIN', 'unit:ownership:write'),
    ('PROPERTY_BOARD_ADMIN', 'unit:read'),
    ('PROPERTY_BOARD_ADMIN', 'unit:write'),
    ('PROPERTY_BOARD_MEMBER', 'document:read'),
    ('PROPERTY_BOARD_MEMBER', 'document:write'),
    ('PROPERTY_BOARD_MEMBER', 'installment:call:write'),
    ('PROPERTY_BOARD_MEMBER', 'installment:read'),
    ('PROPERTY_BOARD_MEMBER', 'invitation:manage'),
    ('PROPERTY_BOARD_MEMBER', 'meeting:manage'),
    ('PROPERTY_BOARD_MEMBER', 'meeting:minutes:publish'),
    ('PROPERTY_BOARD_MEMBER', 'meeting:read'),
    ('PROPERTY_BOARD_MEMBER', 'messaging:broadcast'),
    ('PROPERTY_BOARD_MEMBER', 'party:invite'),
    ('PROPERTY_BOARD_MEMBER', 'party:read'),
    ('PROPERTY_BOARD_MEMBER', 'party:write'),
    ('PROPERTY_BOARD_MEMBER', 'property:accounting:read'),
    ('PROPERTY_BOARD_MEMBER', 'property:accounting:write'),
    ('PROPERTY_BOARD_MEMBER', 'property:board:manage'),
    ('PROPERTY_BOARD_MEMBER', 'property:create'),
    ('PROPERTY_BOARD_MEMBER', 'property:member:invite'),
    ('PROPERTY_BOARD_MEMBER', 'property:read'),
    ('PROPERTY_BOARD_MEMBER', 'property:update'),
    ('PROPERTY_BOARD_MEMBER', 'unit:ownership:write'),
    ('PROPERTY_BOARD_MEMBER', 'unit:read'),
    ('PROPERTY_BOARD_MEMBER', 'unit:write'),
    ('PROPERTY_MANAGER_ADMIN', 'document:read'),
    ('PROPERTY_MANAGER_ADMIN', 'document:write'),
    ('PROPERTY_MANAGER_ADMIN', 'installment:call:write'),
    ('PROPERTY_MANAGER_ADMIN', 'installment:read'),
    ('PROPERTY_MANAGER_ADMIN', 'invitation:manage'),
    ('PROPERTY_MANAGER_ADMIN', 'meeting:manage'),
    ('PROPERTY_MANAGER_ADMIN', 'meeting:minutes:publish'),
    ('PROPERTY_MANAGER_ADMIN', 'meeting:read'),
    ('PROPERTY_MANAGER_ADMIN', 'messaging:broadcast'),
    ('PROPERTY_MANAGER_ADMIN', 'party:invite'),
    ('PROPERTY_MANAGER_ADMIN', 'party:read'),
    ('PROPERTY_MANAGER_ADMIN', 'party:write'),
    ('PROPERTY_MANAGER_ADMIN', 'property:accounting:read'),
    ('PROPERTY_MANAGER_ADMIN', 'property:accounting:write'),
    ('PROPERTY_MANAGER_ADMIN', 'property:board:manage'),
    ('PROPERTY_MANAGER_ADMIN', 'property:create'),
    ('PROPERTY_MANAGER_ADMIN', 'property:member:invite'),
    ('PROPERTY_MANAGER_ADMIN', 'property:read'),
    ('PROPERTY_MANAGER_ADMIN', 'property:update'),
    ('PROPERTY_MANAGER_ADMIN', 'unit:ownership:write'),
    ('PROPERTY_MANAGER_ADMIN', 'unit:read'),
    ('PROPERTY_MANAGER_ADMIN', 'unit:write'),
    ('PROPERTY_MANAGER_MEMBER', 'document:read'),
    ('PROPERTY_MANAGER_MEMBER', 'document:write'),
    ('PROPERTY_MANAGER_MEMBER', 'installment:call:write'),
    ('PROPERTY_MANAGER_MEMBER', 'installment:read'),
    ('PROPERTY_MANAGER_MEMBER', 'invitation:manage'),
    ('PROPERTY_MANAGER_MEMBER', 'meeting:manage'),
    ('PROPERTY_MANAGER_MEMBER', 'meeting:minutes:publish'),
    ('PROPERTY_MANAGER_MEMBER', 'meeting:read'),
    ('PROPERTY_MANAGER_MEMBER', 'messaging:broadcast'),
    ('PROPERTY_MANAGER_MEMBER', 'party:invite'),
    ('PROPERTY_MANAGER_MEMBER', 'party:read'),
    ('PROPERTY_MANAGER_MEMBER', 'party:write'),
    ('PROPERTY_MANAGER_MEMBER', 'property:accounting:read'),
    ('PROPERTY_MANAGER_MEMBER', 'property:accounting:write'),
    ('PROPERTY_MANAGER_MEMBER', 'property:board:manage'),
    ('PROPERTY_MANAGER_MEMBER', 'property:create'),
    ('PROPERTY_MANAGER_MEMBER', 'property:member:invite'),
    ('PROPERTY_MANAGER_MEMBER', 'property:read'),
    ('PROPERTY_MANAGER_MEMBER', 'property:update'),
    ('PROPERTY_MANAGER_MEMBER', 'unit:ownership:write'),
    ('PROPERTY_MANAGER_MEMBER', 'unit:read'),
    ('PROPERTY_MANAGER_MEMBER', 'unit:write'),
    ('PROPERTY_OWNER', 'document:read'),
    ('PROPERTY_OWNER', 'installment:read'),
    ('PROPERTY_OWNER', 'meeting:read'),
    ('PROPERTY_OWNER', 'party:read'),
    ('PROPERTY_OWNER', 'unit:read'),
    ('ROLE_ADMIN', 'document:read'),
    ('ROLE_ADMIN', 'document:write'),
    ('ROLE_ADMIN', 'installment:call:write'),
    ('ROLE_ADMIN', 'installment:read'),
    ('ROLE_ADMIN', 'invitation:manage'),
    ('ROLE_ADMIN', 'meeting:manage'),
    ('ROLE_ADMIN', 'meeting:minutes:publish'),
    ('ROLE_ADMIN', 'meeting:read'),
    ('ROLE_ADMIN', 'messaging:broadcast'),
    ('ROLE_ADMIN', 'party:invite'),
    ('ROLE_ADMIN', 'party:read'),
    ('ROLE_ADMIN', 'party:write'),
    ('ROLE_ADMIN', 'property:accounting:read'),
    ('ROLE_ADMIN', 'property:accounting:write'),
    ('ROLE_ADMIN', 'property:board:manage'),
    ('ROLE_ADMIN', 'property:create'),
    ('ROLE_ADMIN', 'property:member:invite'),
    ('ROLE_ADMIN', 'property:read'),
    ('ROLE_ADMIN', 'property:update'),
    ('ROLE_ADMIN', 'unit:ownership:write'),
    ('ROLE_ADMIN', 'unit:read'),
    ('ROLE_ADMIN', 'unit:write'),
    ('ROLE_ADMIN', 'user:admin');
