-- =========================================================================
-- V20: volunteer-syndic onboarding wizard.
--
-- 1. onboarding_lead: the email typed on step 1 of the wizard, captured
--    before any account can exist. The account itself is only created at the
--    end of step 2, because a Party is property-scoped (party.property_id is
--    NOT NULL) and the property has no name before that step - so without
--    this table every visitor abandoning between step 1 and step 2 would be
--    lost. converted_at is stamped when the same email finally registers,
--    so the follow-up job can skip converted leads.
--    Keyed by email (unique): retyping the same address updates the row
--    instead of piling up duplicates.
--
-- 2. ledger_account.bank_account_number: the bank's own account reference
--    (RIB/IBAN...), free text on purpose - accounts may be foreign and the
--    app does not clear payments itself. NOT to be confused with
--    ledger_account.account_number, which is the accounting number
--    (514100 + per-property increment, ADR 0001) generated by the system.
-- =========================================================================

CREATE TABLE onboarding_lead (
    id                 UUID PRIMARY KEY,
    email              VARCHAR(150) NOT NULL,
    first_name         VARCHAR(100),
    last_name          VARCHAR(100),
    converted_at       TIMESTAMPTZ,
    created_date       TIMESTAMPTZ NOT NULL,
    last_modified_date TIMESTAMPTZ NOT NULL,
    version            BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_onboarding_lead_email UNIQUE (email)
);

-- Drives the follow-up job ("leads not converted yet").
CREATE INDEX idx_onboarding_lead_converted_at ON onboarding_lead (converted_at);

ALTER TABLE ledger_account ADD COLUMN bank_account_number VARCHAR(64);
