import type { Paged } from '@/shared/types/pagination.types';

/**
 * Mirrors oikos-api's DocumentOwnerType, restricted to what this app attaches
 * things to. PAYMENT, CONVOCATION and MEETING_MINUTES are absent on purpose:
 * those documents are generated by the API and downloaded through their own
 * endpoints, never uploaded here.
 */
export const DOCUMENT_OWNER_TYPES = ['PROPERTY', 'UNIT', 'GENERAL_MEETING', 'AGENDA_ITEM'] as const;
export type DocumentOwnerType = (typeof DOCUMENT_OWNER_TYPES)[number];

export interface Document {
  id: string;
  ownerType: DocumentOwnerType;
  ownerId: string;
  fileName: string;
  contentType: string;
  sizeBytes: number;
  uploadedBy: string;
  uploadedAt: string;
}

export type PagedDocuments = Paged<Document>;
